name: Newman Run

on:
  schedule: 
      - cron: 30 15 * * 1-5 

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: definight/postman_api_trello_testing@master
        with:
          apiKey: ${{ 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 }}
          collection: trelloCol.json
          environment: trelloEnv.json
