# This is a basic workflow to help you get started with Actions

name: Scheduled test run

# Controls when the workflow will run
on:
  schedule: 
      - cron: 30 13 * * 0-6 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Create a directory for the report
        run: |
          mkdir htmlReportExtra
      
      - name: Use Node.js  
        uses: actions/setup-node@v3
      # Runs a single command using the runners shell
      - name: Install Newman
        run: | 
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run a collection
        run: | 
          newman run trelloCol.json -e trelloEnv.json -r htmlextra --reporter-htmlextra-export htmlReportExtra/report.html
          
      - name: Publish the report
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: htmlReportExtra
